---
name: CI

on:
  push:
    branches:
      - uat
    tags:
      - rebuild-uat

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Show date
        run: date

      - name: Show content
        run: cat content
