---
name: CI

on:
  push:
    branches:
      - uat
  repository_dispatch:
    types:
      - rebuild-uat

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Show date
        run: date
